// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: post_reads.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const checkPostRead = `-- name: CheckPostRead :one
SELECT user_id, post_id, read_at from post_reads
WHERE user_id = $1 AND post_id = $2
`

type CheckPostReadParams struct {
	UserID uuid.UUID
	PostID uuid.UUID
}

func (q *Queries) CheckPostRead(ctx context.Context, arg CheckPostReadParams) (PostRead, error) {
	row := q.db.QueryRowContext(ctx, checkPostRead, arg.UserID, arg.PostID)
	var i PostRead
	err := row.Scan(&i.UserID, &i.PostID, &i.ReadAt)
	return i, err
}

const getPostReadsPerUser = `-- name: GetPostReadsPerUser :many
SELECT posts.id, posts.title, posts.url, posts.description, posts.feed_id, posts.created_at, posts.updated_at, posts.published_at 
FROM post_reads
INNER JOIN posts ON post_reads.post_id = posts.id
WHERE post_reads.user_id = $1
ORDER BY post_reads.read_at DESC
`

func (q *Queries) GetPostReadsPerUser(ctx context.Context, userID uuid.UUID) ([]Post, error) {
	rows, err := q.db.QueryContext(ctx, getPostReadsPerUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Post
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Url,
			&i.Description,
			&i.FeedID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markPostRead = `-- name: MarkPostRead :exec
INSERT INTO post_reads (user_id,post_id) VALUES (
    $1,
    $2
)
`

type MarkPostReadParams struct {
	UserID uuid.UUID
	PostID uuid.UUID
}

func (q *Queries) MarkPostRead(ctx context.Context, arg MarkPostReadParams) error {
	_, err := q.db.ExecContext(ctx, markPostRead, arg.UserID, arg.PostID)
	return err
}
