// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: refresh_tokens.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createRefreshToken = `-- name: CreateRefreshToken :one
INSERT INTO refresh_tokens (refresh_token,expires_at,user_id)
VALUES (
    $1,
    $2,
    $3
)
RETURNING refresh_token, created_at, updated_at, expires_at, revoked_at, user_id
`

type CreateRefreshTokenParams struct {
	RefreshToken string
	ExpiresAt    time.Time
	UserID       uuid.UUID
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRowContext(ctx, createRefreshToken, arg.RefreshToken, arg.ExpiresAt, arg.UserID)
	var i RefreshToken
	err := row.Scan(
		&i.RefreshToken,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.UserID,
	)
	return i, err
}

const getUserFromRefreshToken = `-- name: GetUserFromRefreshToken :one
SELECT users.id, users.name, users.email, users.hashed_password, users.created_at, users.updated_at FROM users
JOIN refresh_tokens on users.id = refresh_tokens.user_id
WHERE refresh_tokens.refresh_token = $1
AND revoked_at IS NULL
AND expires_at > NOW()
`

func (q *Queries) GetUserFromRefreshToken(ctx context.Context, refreshToken string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserFromRefreshToken, refreshToken)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.HashedPassword,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :exec
UPDATE refresh_tokens
SET revoked_at = NOW(), updated_at = NOW()
WHERE refresh_token = $1
`

func (q *Queries) RevokeRefreshToken(ctx context.Context, refreshToken string) error {
	_, err := q.db.ExecContext(ctx, revokeRefreshToken, refreshToken)
	return err
}
